FROM openjdk:8-jdk-alpine
COPY target/filmes-core-1.0-SNAPSHOT-jar-with-dependencies.jar filmes-core-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT java -jar filmes-core-1.0-SNAPSHOT-jar-with-dependencies.jar